<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Movie;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPopular($page = 1, $limit = 20)
    {
        $query = $this->createQueryBuilder('m')
            ->from('Movie', 'm')
            ->orderBy('m.popularity', 'DESC')
            ->setMaxResults($limit)
            ->setFirstResult($page);


    }
}
