<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Movie;
use AppBundle\Entity\User;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPopularQuery()
    {
        $query = $this->createQueryBuilder('m')
            ->orderBy('m.popularity', 'DESC');

        return $query->getQuery();
    }

    public function findRecentQuery()
    {
        $query = $this->createQueryBuilder('m')
            ->orderBy('m.releaseDate', 'DESC');

        return $query->getQuery();
    }

    public function search($data)
    {
        $query = $this->createQueryBuilder('m')
            ->where('m.title LIKE :title')
            ->setParameter('title', '%' . $data . '%')
            ->orderBy('m.id', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
