<?php

namespace AppBundle\Repository;

/**
 * NotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotationRepository extends \Doctrine\ORM\EntityRepository
{
}
